import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export interface TourStep {
  targetId: string
  title: string
  description: string
  position?: 'top' | 'bottom' | 'left' | 'right'
}

export const TOUR_STEPS: TourStep[] = [
  {
    targetId: 'tour-alerts',
    title: 'Autonomous Alerts Feed',
    description: 'Monitor real-time alerts generated by autonomous agents. Critical incidents will automatically surface here.',
    position: 'right'
  },
  {
    targetId: 'tour-map',
    title: 'Operational Map',
    description: 'Visualize all active nodes and incidents geographically. Click on map markers for detailed diagnostics.',
    position: 'bottom'
  },
  {
    targetId: 'tour-chat',
    title: 'AI Coordinator Chat',
    description: 'Interact with your dedicated AI coordination agent. Ask for situation reports or direct agents to investigate.',
    position: 'left'
  },
  {
    targetId: 'tour-header-admin',
    title: 'System Diagnostics & Admin',
    description: 'Access backend diagnostics, telemetry, and override controls by opening the admin panel.',
    position: 'bottom'
  }
]

interface TourState {
  hasCompletedTour: boolean
  isActive: boolean
  currentStepIndex: number
  startTour: () => void
  endTour: () => void
  nextStep: () => void
  prevStep: () => void
  skipTour: () => void
}

export const useTourStore = create<TourState>()(
  persist(
    (set, get) => ({
      hasCompletedTour: false,
      isActive: false,
      currentStepIndex: 0,
      
      startTour: () => set({ isActive: true, currentStepIndex: 0 }),
      
      endTour: () => set({ 
        isActive: false, 
        hasCompletedTour: true 
      }),
      
      nextStep: () => {
        const { currentStepIndex } = get()
        if (currentStepIndex < TOUR_STEPS.length - 1) {
          set({ currentStepIndex: currentStepIndex + 1 })
        } else {
          get().endTour()
        }
      },
      
      prevStep: () => {
        const { currentStepIndex } = get()
        if (currentStepIndex > 0) {
          set({ currentStepIndex: currentStepIndex - 1 })
        }
      },
      
      skipTour: () => set({ 
        isActive: false, 
        hasCompletedTour: true 
      })
    }),
    {
      name: 'beacon-tour-storage',
      // We only want to persist whether they've completed/skipped the tour
      partialize: (state) => ({ hasCompletedTour: state.hasCompletedTour }),
    }
  )
)
